import type { RoleId } from "@/lib/theme/roles";

/**
 * Highlight groups shared by the Vim and Neovim exporters. Keeping one table
 * means the two colorschemes can't drift apart.
 */
export type HlSpec = {
  fg?: RoleId;
  bg?: RoleId;
  /** Undercurl / underline color. */
  sp?: RoleId;
  style?: ("bold" | "italic" | "underline" | "undercurl" | "reverse" | "strikethrough")[];
  /** Emit `hi link` instead of a color definition. */
  link?: string;
};

export type GroupTable = [string, HlSpec][];

/** Classic groups — understood by Vim and Neovim alike. */
export const CORE_GROUPS: GroupTable = [
  // ── interface ──
  ["Normal", { fg: "fg", bg: "bg" }],
  ["NormalNC", { fg: "fg", bg: "bg" }],
  ["NormalFloat", { fg: "fg", bg: "bgAlt" }],
  ["FloatBorder", { fg: "border", bg: "bgAlt" }],
  ["FloatTitle", { fg: "accent", bg: "bgAlt", style: ["bold"] }],
  ["Cursor", { fg: "bg", bg: "cursor" }],
  ["lCursor", { fg: "bg", bg: "cursor" }],
  ["CursorLine", { bg: "currentLine" }],
  ["CursorColumn", { bg: "currentLine" }],
  ["ColorColumn", { bg: "currentLine" }],
  ["CursorLineNr", { fg: "lineNumberActive", style: ["bold"] }],
  ["LineNr", { fg: "lineNumber" }],
  ["SignColumn", { fg: "lineNumber", bg: "bg" }],
  ["FoldColumn", { fg: "lineNumber", bg: "bg" }],
  ["Folded", { fg: "fgDim", bg: "currentLine" }],
  ["VertSplit", { fg: "border", bg: "bg" }],
  ["WinSeparator", { fg: "border", bg: "bg" }],
  ["StatusLine", { fg: "fg", bg: "bgAlt" }],
  ["StatusLineNC", { fg: "fgDim", bg: "bgAlt" }],
  ["WinBar", { fg: "fg", bg: "bg", style: ["bold"] }],
  ["WinBarNC", { fg: "fgDim", bg: "bg" }],
  ["TabLine", { fg: "fgDim", bg: "bgAlt" }],
  ["TabLineFill", { fg: "fgDim", bg: "bgAlt" }],
  ["TabLineSel", { fg: "fg", bg: "bg", style: ["bold"] }],
  ["Pmenu", { fg: "fg", bg: "bgAlt" }],
  ["PmenuSel", { fg: "fg", bg: "selection", style: ["bold"] }],
  ["PmenuSbar", { bg: "bgAlt" }],
  ["PmenuThumb", { bg: "border" }],
  ["PmenuKind", { fg: "type", bg: "bgAlt" }],
  ["PmenuExtra", { fg: "fgDim", bg: "bgAlt" }],
  ["WildMenu", { fg: "bg", bg: "accent" }],
  ["Visual", { bg: "selection" }],
  ["VisualNOS", { bg: "selection" }],
  ["Search", { fg: "fg", bg: "matchBg" }],
  ["IncSearch", { fg: "bg", bg: "accent" }],
  ["CurSearch", { fg: "bg", bg: "accent" }],
  ["Substitute", { fg: "bg", bg: "warning" }],
  ["MatchParen", { fg: "accent", style: ["bold", "underline"] }],
  ["NonText", { fg: "lineNumber" }],
  ["Whitespace", { fg: "lineNumber" }],
  ["SpecialKey", { fg: "lineNumber" }],
  ["EndOfBuffer", { fg: "bg" }],
  ["Conceal", { fg: "fgDim" }],
  ["Directory", { fg: "function" }],
  ["Title", { fg: "accent", style: ["bold"] }],
  ["Question", { fg: "success" }],
  ["MoreMsg", { fg: "success" }],
  ["ModeMsg", { fg: "fg", style: ["bold"] }],
  ["MsgArea", { fg: "fg" }],
  ["ErrorMsg", { fg: "error" }],
  ["WarningMsg", { fg: "warning" }],
  ["QuickFixLine", { bg: "selection" }],
  ["Underlined", { fg: "info", style: ["underline"] }],
  ["Ignore", { fg: "fgDim" }],

  // ── syntax ──
  ["Comment", { fg: "comment", style: ["italic"] }],
  ["Constant", { fg: "constant" }],
  ["String", { fg: "string" }],
  ["Character", { fg: "string" }],
  ["Number", { fg: "number" }],
  ["Boolean", { fg: "constant" }],
  ["Float", { fg: "number" }],
  ["Identifier", { fg: "variable" }],
  ["Function", { fg: "function" }],
  ["Statement", { fg: "keyword" }],
  ["Conditional", { fg: "keyword" }],
  ["Repeat", { fg: "keyword" }],
  ["Label", { fg: "keyword" }],
  ["Operator", { fg: "operator" }],
  ["Keyword", { fg: "keyword" }],
  ["Exception", { fg: "keyword" }],
  ["PreProc", { fg: "attribute" }],
  ["Include", { fg: "keyword" }],
  ["Define", { fg: "attribute" }],
  ["Macro", { fg: "attribute" }],
  ["PreCondit", { fg: "attribute" }],
  ["Type", { fg: "type" }],
  ["StorageClass", { fg: "storage" }],
  ["Structure", { fg: "type" }],
  ["Typedef", { fg: "type" }],
  ["Special", { fg: "escape" }],
  ["SpecialChar", { fg: "escape" }],
  ["Tag", { fg: "tag" }],
  ["Delimiter", { fg: "punctuation" }],
  ["SpecialComment", { fg: "comment", style: ["bold", "italic"] }],
  ["Debug", { fg: "warning" }],
  ["Todo", { fg: "bg", bg: "warning", style: ["bold"] }],
  ["Error", { fg: "error" }],

  // ── diff & spell ──
  ["DiffAdd", { fg: "success", bg: "currentLine" }],
  ["DiffChange", { fg: "warning", bg: "currentLine" }],
  ["DiffDelete", { fg: "error", bg: "currentLine" }],
  ["DiffText", { fg: "bg", bg: "warning" }],
  ["Added", { fg: "success" }],
  ["Changed", { fg: "warning" }],
  ["Removed", { fg: "error" }],
  ["SpellBad", { sp: "error", style: ["undercurl"] }],
  ["SpellCap", { sp: "warning", style: ["undercurl"] }],
  ["SpellLocal", { sp: "info", style: ["undercurl"] }],
  ["SpellRare", { sp: "success", style: ["undercurl"] }],
];

/** Treesitter captures and LSP semantic tokens — Neovim only. */
export const TREESITTER_GROUPS: GroupTable = [
  ["@comment", { fg: "comment", style: ["italic"] }],
  ["@comment.documentation", { fg: "comment", style: ["italic"] }],
  ["@comment.error", { fg: "error", style: ["bold"] }],
  ["@comment.todo", { fg: "bg", bg: "warning", style: ["bold"] }],
  ["@comment.note", { fg: "bg", bg: "info", style: ["bold"] }],

  ["@keyword", { fg: "keyword" }],
  ["@keyword.function", { fg: "storage" }],
  ["@keyword.operator", { fg: "operator" }],
  ["@keyword.return", { fg: "keyword" }],
  ["@keyword.import", { fg: "keyword" }],
  ["@keyword.exception", { fg: "keyword" }],
  ["@keyword.conditional", { fg: "keyword" }],
  ["@keyword.repeat", { fg: "keyword" }],
  ["@keyword.modifier", { fg: "storage" }],
  ["@keyword.type", { fg: "storage" }],

  ["@string", { fg: "string" }],
  ["@string.documentation", { fg: "string" }],
  ["@string.escape", { fg: "escape", style: ["bold"] }],
  ["@string.regexp", { fg: "escape" }],
  ["@string.special", { fg: "escape" }],
  ["@character", { fg: "string" }],
  ["@character.special", { fg: "escape" }],

  ["@number", { fg: "number" }],
  ["@number.float", { fg: "number" }],
  ["@boolean", { fg: "constant" }],
  ["@constant", { fg: "constant" }],
  ["@constant.builtin", { fg: "constant" }],
  ["@constant.macro", { fg: "attribute" }],

  ["@function", { fg: "function" }],
  ["@function.call", { fg: "function" }],
  ["@function.builtin", { fg: "function", style: ["italic"] }],
  ["@function.macro", { fg: "attribute" }],
  ["@function.method", { fg: "function" }],
  ["@function.method.call", { fg: "function" }],
  ["@constructor", { fg: "type" }],

  ["@type", { fg: "type" }],
  ["@type.builtin", { fg: "type", style: ["italic"] }],
  ["@type.definition", { fg: "type" }],
  ["@module", { fg: "type" }],
  ["@namespace", { fg: "type" }],
  ["@attribute", { fg: "attribute" }],
  ["@label", { fg: "keyword" }],

  ["@variable", { fg: "variable" }],
  ["@variable.builtin", { fg: "storage", style: ["italic"] }],
  ["@variable.parameter", { fg: "parameter" }],
  ["@variable.member", { fg: "property" }],
  ["@property", { fg: "property" }],
  ["@field", { fg: "property" }],
  ["@parameter", { fg: "parameter" }],

  ["@operator", { fg: "operator" }],
  ["@punctuation.delimiter", { fg: "punctuation" }],
  ["@punctuation.bracket", { fg: "punctuation" }],
  ["@punctuation.special", { fg: "escape" }],

  ["@tag", { fg: "tag" }],
  ["@tag.builtin", { fg: "tag" }],
  ["@tag.attribute", { fg: "attribute" }],
  ["@tag.delimiter", { fg: "punctuation" }],

  ["@markup.heading", { fg: "accent", style: ["bold"] }],
  ["@markup.strong", { fg: "fg", style: ["bold"] }],
  ["@markup.italic", { fg: "fg", style: ["italic"] }],
  ["@markup.link", { fg: "info", style: ["underline"] }],
  ["@markup.link.url", { fg: "info", style: ["underline"] }],
  ["@markup.raw", { fg: "string" }],
  ["@markup.list", { fg: "keyword" }],
  ["@markup.quote", { fg: "comment", style: ["italic"] }],

  ["@diff.plus", { fg: "success" }],
  ["@diff.minus", { fg: "error" }],
  ["@diff.delta", { fg: "warning" }],

  // LSP semantic tokens
  ["@lsp.type.namespace", { fg: "type" }],
  ["@lsp.type.class", { fg: "type" }],
  ["@lsp.type.enum", { fg: "type" }],
  ["@lsp.type.interface", { fg: "type" }],
  ["@lsp.type.struct", { fg: "type" }],
  ["@lsp.type.typeParameter", { fg: "type" }],
  ["@lsp.type.type", { fg: "type" }],
  ["@lsp.type.parameter", { fg: "parameter" }],
  ["@lsp.type.variable", { fg: "variable" }],
  ["@lsp.type.property", { fg: "property" }],
  ["@lsp.type.enumMember", { fg: "constant" }],
  ["@lsp.type.function", { fg: "function" }],
  ["@lsp.type.method", { fg: "function" }],
  ["@lsp.type.macro", { fg: "attribute" }],
  ["@lsp.type.decorator", { fg: "attribute" }],
  ["@lsp.type.keyword", { fg: "keyword" }],
  ["@lsp.type.comment", { fg: "comment", style: ["italic"] }],
  ["@lsp.type.string", { fg: "string" }],
  ["@lsp.type.number", { fg: "number" }],
  ["@lsp.type.operator", { fg: "operator" }],
  ["@lsp.typemod.variable.readonly", { fg: "constant" }],
  ["@lsp.typemod.variable.defaultLibrary", { fg: "storage", style: ["italic"] }],
];

/** Diagnostics plus the plugins nearly everyone has installed. */
export const NVIM_EXTRA_GROUPS: GroupTable = [
  ["DiagnosticError", { fg: "error" }],
  ["DiagnosticWarn", { fg: "warning" }],
  ["DiagnosticInfo", { fg: "info" }],
  ["DiagnosticHint", { fg: "success" }],
  ["DiagnosticOk", { fg: "success" }],
  ["DiagnosticUnderlineError", { sp: "error", style: ["undercurl"] }],
  ["DiagnosticUnderlineWarn", { sp: "warning", style: ["undercurl"] }],
  ["DiagnosticUnderlineInfo", { sp: "info", style: ["undercurl"] }],
  ["DiagnosticUnderlineHint", { sp: "success", style: ["undercurl"] }],
  ["DiagnosticVirtualTextError", { fg: "error", bg: "bg" }],
  ["DiagnosticVirtualTextWarn", { fg: "warning", bg: "bg" }],
  ["DiagnosticVirtualTextInfo", { fg: "info", bg: "bg" }],
  ["DiagnosticVirtualTextHint", { fg: "success", bg: "bg" }],
  ["LspReferenceText", { bg: "selection" }],
  ["LspReferenceRead", { bg: "selection" }],
  ["LspReferenceWrite", { bg: "selection", style: ["underline"] }],
  ["LspInlayHint", { fg: "lineNumber", bg: "bg", style: ["italic"] }],

  ["GitSignsAdd", { fg: "success" }],
  ["GitSignsChange", { fg: "warning" }],
  ["GitSignsDelete", { fg: "error" }],

  ["TelescopeNormal", { fg: "fg", bg: "bgAlt" }],
  ["TelescopeBorder", { fg: "border", bg: "bgAlt" }],
  ["TelescopeTitle", { fg: "bg", bg: "accent", style: ["bold"] }],
  ["TelescopeSelection", { bg: "selection", style: ["bold"] }],
  ["TelescopeMatching", { fg: "accent", style: ["bold"] }],

  ["NvimTreeNormal", { fg: "fgDim", bg: "bgAlt" }],
  ["NvimTreeRootFolder", { fg: "accent", style: ["bold"] }],
  ["NvimTreeFolderName", { fg: "function" }],
  ["NvimTreeOpenedFileIcon", { fg: "accent" }],
  ["NvimTreeGitDirty", { fg: "warning" }],
  ["NvimTreeGitNew", { fg: "success" }],
  ["NvimTreeGitDeleted", { fg: "error" }],

  ["CmpItemAbbr", { fg: "fg" }],
  ["CmpItemAbbrMatch", { fg: "accent", style: ["bold"] }],
  ["CmpItemKind", { fg: "type" }],
  ["CmpItemMenu", { fg: "fgDim" }],

  ["WhichKey", { fg: "accent" }],
  ["WhichKeyGroup", { fg: "function" }],
  ["WhichKeyDesc", { fg: "fg" }],
  ["WhichKeySeparator", { fg: "comment" }],
  ["WhichKeyFloat", { bg: "bgAlt" }],

  ["IndentBlanklineChar", { fg: "border" }],
  ["IblIndent", { fg: "border" }],
  ["IblScope", { fg: "accent" }],
];
