import type { LangId } from "./tokenize";

/**
 * Sample code is chosen to exercise every syntax role — comments, strings with
 * escapes, numbers, types, decorators, markup — so no color hides until you're
 * three files into a real project.
 */
export const SAMPLES: Record<LangId, string> = {
  tsx: `import { useMemo, useState } from "react";
import { oklch, type Palette } from "@/lib/color";

const DEFAULT_HUE = 268;
const SCHEMES = ["spectrum", "analogous", "triadic"] as const;

export interface ThemeOptions {
  hue: number;
  chroma?: number;
  appearance: "dark" | "light";
}

/**
 * Derive a full palette from a single hue.
 * Returns memoized swatches — never recomputes on hover.
 */
export function useTheme({ hue = DEFAULT_HUE, appearance }: ThemeOptions) {
  const [scheme, setScheme] = useState<(typeof SCHEMES)[number]>("spectrum");
  const isDark = appearance === "dark";

  const palette = useMemo<Palette>(() => {
    return oklch.spread(hue, 8, scheme).map((h, i) => ({
      hex: oklch.toHex({ l: isDark ? 0.79 : 0.52, c: 0.13, h }),
      label: \`slot-\${i}\`, // e.g. "slot-3"
    }));
  }, [hue, scheme, isDark]);

  return (
    <section className="grid" data-appearance={appearance}>
      {palette.map(({ hex, label }) => (
        <button key={label} style={{ background: hex }} onClick={() => setScheme("triadic")}>
          <span className="mono">{hex}</span>
        </button>
      ))}
    </section>
  );
}
`,

  python: `"""Generate a terminal palette that survives daylight."""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Iterable, Optional

WCAG_AA = 4.5
ANSI_HUES = (27.0, 148.0, 90.0, 255.0, 328.0, 200.0)


@dataclass(frozen=True)
class Swatch:
    hex: str
    role: str
    locked: bool = False
    tags: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.hex.startswith("#"):
            raise ValueError(f"expected a hex color, got {self.hex!r}")


def contrast(fg: str, bg: str) -> float:
    """Relative luminance ratio, 1.0 .. 21.0."""
    lf, lb = luminance(fg), luminance(bg)
    hi, lo = max(lf, lb), min(lf, lb)
    return (hi + 0.05) / (lo + 0.05)


def build(base: float = 268.0, dark: bool = True) -> Iterable[Swatch]:
    lightness = 0.79 if dark else 0.52
    for index, hue in enumerate(ANSI_HUES):
        shifted = math.fmod(base + hue, 360.0)
        yield Swatch(hex=to_hex(lightness, 0.13, shifted), role=f"ansi{index}")
`,

  rust: `//! Perceptual color space conversions. No dependencies, no allocations.

use std::fmt;

const EPSILON: f64 = 0.000_1;
const CUBE: [u8; 6] = [0, 95, 135, 175, 215, 255];

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Oklch {
    pub l: f64,
    pub c: f64,
    pub h: f64,
}

pub trait Perceptual {
    fn lighten(&self, amount: f64) -> Self;
    fn contrast_against(&self, other: &Self) -> f64;
}

impl Perceptual for Oklch {
    fn lighten(&self, amount: f64) -> Self {
        Oklch { l: (self.l + amount).clamp(0.0, 1.0), ..*self }
    }

    fn contrast_against(&self, other: &Self) -> f64 {
        let (hi, lo) = if self.l > other.l { (self, other) } else { (other, self) };
        (hi.l + 0.05) / (lo.l + 0.05)
    }
}

impl fmt::Display for Oklch {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "oklch({:.3} {:.3} {:.1})", self.l, self.c, self.h)
    }
}

pub fn nearest_xterm(rgb: (u8, u8, u8)) -> Option<u8> {
    CUBE.iter().enumerate().map(|(i, _)| i as u8 + 16).min_by_key(|&i| {
        let delta = i32::from(rgb.0) - i32::from(i);
        delta.pow(2)
    })
}
`,

  go: `// Package theme renders editor colorschemes for every target we support.
package theme

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	Version  = "1.0.0"
	MaxRoles = 48
)

// Theme is the neutral shape every exporter reads from.
type Theme struct {
	Name       string            \`json:"name"\`
	Appearance string            \`json:"appearance"\`
	Colors     map[string]string \`json:"colors"\`
}

type Exporter interface {
	Render(t *Theme) (string, error)
	Filename(t *Theme) string
}

func (t *Theme) IsDark() bool {
	return strings.EqualFold(t.Appearance, "dark")
}

// Export writes the theme for every registered target.
func Export(t *Theme, targets []Exporter) (map[string]string, error) {
	out := make(map[string]string, len(targets))
	for _, target := range targets {
		body, err := target.Render(t)
		if err != nil {
			return nil, fmt.Errorf("render %T: %w", target, err)
		}
		out[target.Filename(t)] = body
	}
	return out, nil
}
`,

  lua: `-- Neovim colorscheme, generated by themephile.dev
-- :colorscheme nocturne

local M = {}

local palette = {
  bg = "#0e1016",
  fg = "#dfe3ec",
  accent = "#b48ef0",
  comment = "#5d6478",
  string = "#8fd47f",
}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.setup(options)
  options = options or {}
  local transparent = options.transparent == true

  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.background = "dark"
  vim.g.colors_name = "nocturne"

  hl("Normal", { fg = palette.fg, bg = transparent and "NONE" or palette.bg })
  hl("Comment", { fg = palette.comment, italic = true })
  hl("String", { fg = palette.string })
  hl("@variable", { fg = palette.fg })

  for index = 0, 15 do
    vim.g["terminal_color_" .. index] = palette.fg
  end
end

return M
`,

  css: `/* Design tokens — the only place colors are allowed to be literals. */

@import "tailwindcss";

:root {
  --ink-0: #06070b;
  --ink-1: #0d0f14;
  --line: rgb(255 255 255 / 7%);
  --accent: oklch(0.79 0.13 268);
  --radius: 0.625rem;
  --font-mono: "Geist Mono", ui-monospace, monospace;
}

@media (prefers-color-scheme: light) {
  :root {
    --ink-0: #fbf8f1;
    --ink-1: #ffffff;
  }
}

.panel {
  background: var(--ink-1);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 1rem 1.25rem;
  transition: border-color 160ms ease-out;
}

.panel:hover,
.panel:focus-within {
  border-color: color-mix(in oklab, var(--accent) 45%, transparent);
}

.panel::after {
  content: "";
  inset: 0;
  position: absolute;
}
`,
};
